#ifndef NYX_KEYCODES_H
#define NYX_KEYCODES_H

#include "SDL2/SDL.h"

#define NYX_KEY_A     SDL_SCANCODE_A
#define NYX_KEY_B     SDL_SCANCODE_B
#define NYX_KEY_C     SDL_SCANCODE_C
#define NYX_KEY_D     SDL_SCANCODE_D
#define NYX_KEY_E     SDL_SCANCODE_E
#define NYX_KEY_F     SDL_SCANCODE_F
#define NYX_KEY_G     SDL_SCANCODE_G
#define NYX_KEY_H     SDL_SCANCODE_H
#define NYX_KEY_I     SDL_SCANCODE_I
#define NYX_KEY_J     SDL_SCANCODE_J
#define NYX_KEY_K     SDL_SCANCODE_K
#define NYX_KEY_L     SDL_SCANCODE_L
#define NYX_KEY_M     SDL_SCANCODE_M
#define NYX_KEY_N     SDL_SCANCODE_N
#define NYX_KEY_O     SDL_SCANCODE_O
#define NYX_KEY_P     SDL_SCANCODE_P
#define NYX_KEY_Q     SDL_SCANCODE_Q
#define NYX_KEY_R     SDL_SCANCODE_R
#define NYX_KEY_S     SDL_SCANCODE_S
#define NYX_KEY_T     SDL_SCANCODE_T
#define NYX_KEY_U     SDL_SCANCODE_U
#define NYX_KEY_V     SDL_SCANCODE_V
#define NYX_KEY_W     SDL_SCANCODE_W
#define NYX_KEY_X     SDL_SCANCODE_X
#define NYX_KEY_Y     SDL_SCANCODE_Y
#define NYX_KEY_Z     SDL_SCANCODE_Z
#define NYX_KEY_LEFT  SDL_SCANCODE_LEFT
#define NYX_KEY_RIGHT SDL_SCANCODE_RIGHT
#define NYX_KEY_UP    SDL_SCANCODE_UP
#define NYX_KEY_DOWN  SDL_SCANCODE_DOWN

#endif
