#ifndef NYX_H
#define NYX_H

#include "nyx/bit.h"
#include "nyx/bitmap.h"
#include "nyx/color.h"
#include "nyx/draw.h"
#include "nyx/error.h"
#include "nyx/event.h"
#include "nyx/file.h"
#include "nyx/font.h"
#include "nyx/geom.h"
#include "nyx/graphics.h"
#include "nyx/kerning.h"
#include "nyx/keyboard.h"
#include "nyx/keycodes.h"
#include "nyx/layer.h"
#include "nyx/linear.h"
#include "nyx/list.h"
#include "nyx/map.h"
#include "nyx/mask.h"
#include "nyx/meta.h"
#include "nyx/pack.h"
#include "nyx/random.h"
#include "nyx/symmetry.h"
#include "nyx/texture.h"
#include "nyx/transform.h"
#include "nyx/view.h"

#endif
