#include "nyx/nyx.h"

#include "_shader.h"

const char *color_shader_src =
        "#define RAMPS 9\n"
        "#define VALUES 5\n"
        "#define GRAN 1\n"

        "uniform vec4 ramps[RAMPS*VALUES];\n"
        "uniform float w;\n"
        "uniform float h;\n"
        "uniform sampler2D al_tex;\n"
        "uniform float squish;\n"

        "varying vec4 varying_color;\n"
        "varying vec2 varying_texcoord;\n"

        "void main(){\n"
        "vec4 color = varying_color * texture2D(al_tex, varying_texcoord);\n"
        "int ramp = int(color.x*256.0);\n"
        "float value = color.y * float(VALUES-1);\n"
        "int dark = int(floor(value));\n"
        "float frac = mod(value, 1.0);\n"
        "if(squish == 0.0)\n"
        "{\n"
        "  if(frac<0.5)\n"
        "    gl_FragColor=ramps[dark+ramp*VALUES];\n"
        "  else"
        "    gl_FragColor=ramps[dark+1+ramp*VALUES];\n"
        "  return;\n"
        "}\n"
        "if(frac<0.5-0.5/squish)\n"
        "{\n"
        "  gl_FragColor=ramps[dark+ramp*VALUES];\n"
        "  return;\n"
        "}\n"
        "else if(frac>=0.5+0.5/squish)\n"
        "{\n"
        "  gl_FragColor=ramps[dark+1+ramp*VALUES];\n"
        "  return;\n"
        "}\n"
        "vec4 darker=ramps[dark+ramp*VALUES];\n"
        "vec4 brighter=ramps[dark+1+ramp*VALUES];\n"
        "int lvl=int(16.0*squish*(frac-(0.5-0.5/squish)));\n"
        "int i = int(mod(floor(varying_texcoord.x*float(w)),4.0)) + int(mod(floor(varying_texcoord.y*float(h)),4.0))*4;\n"
        "if(i==0)\n"
        "  gl_FragColor = lvl>0?brighter:darker;\n"
        "else if(i==1)\n"
        "  gl_FragColor = lvl>8?brighter:darker;\n"
        "else if(i==2)\n"
        "  gl_FragColor = lvl>2?brighter:darker;\n"
        "else if(i==3)\n"
        "  gl_FragColor = lvl>10?brighter:darker;\n"
        "else if(i==4)\n"
        "  gl_FragColor = lvl>14?brighter:darker;\n"
        "else if(i==5)\n"
        "  gl_FragColor = lvl>4?brighter:darker;\n"
        "else if(i==6)\n"
        "  gl_FragColor = lvl>12?brighter:darker;\n"
        "else if(i==7)\n"
        "  gl_FragColor = lvl>6?brighter:darker;\n"
        "else if(i==8)\n"
        "  gl_FragColor = lvl>3?brighter:darker;\n"
        "else if(i==9)\n"
        "  gl_FragColor = lvl>11?brighter:darker;\n"
        "else if(i==10)\n"
        "  gl_FragColor = lvl>1?brighter:darker;\n"
        "else if(i==11)\n"
        "  gl_FragColor = lvl>9?brighter:darker;\n"
        "else if(i==12)\n"
        "  gl_FragColor = lvl>13?brighter:darker;\n"
        "else if(i==13)\n"
        "  gl_FragColor = lvl>7?brighter:darker;\n"
        "else if(i==14)\n"
        "  gl_FragColor = lvl>15?brighter:darker;\n"
        "else if(i==15)\n"
        "  gl_FragColor = lvl>5?brighter:darker;\n"
        "};";
